{
 "title": "Vast",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "idle_gpus",
    "label": "Idle GPUs",
    "query": "SELECT\n  count(*)\nFROM instance\nWHERE\n  earning = '0'\nGROUP BY time\nORDER BY time desc\nlimit 1"
   },
   { "name": "power_offset", "label": "Power Offset", "query": "250" },
   { "name": "power_cost", "label": "Power Cost", "query": "0.35" },
   { "name": "machine_id", "label": "Machine ID", "query": "2681" }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  component AS metric,\n  utilisation\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'cpu' AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "RAM Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  component AS metric,\n  utilisation\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'ram' AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Current Rentals",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  rentals_bid AS \"Bid\",\n  rentals_on_demand AS \"On Demand\",\n  rentals_stored AS \"Stored\"\nFROM machine\nWHERE\n  $__unixEpochFilter(time) AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  count(*) as \"Idle GPUs\"\nFROM instance\nWHERE\n  earning = '0'\nGROUP BY time\nORDER BY time desc\nlimit 1"
    }
   ]
  },
  {
   "title": "Free space",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  component AS metric,\n  utilisation\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'disk_space' AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Power draw",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  sum(power_consumption) + $power_offset AS \"power_consumption\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) and\n  machine_id = $machine_id\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "title": "Credit earned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  account_credit\nFROM machine\nWHERE\n  $__unixEpochFilter(time)\n  and machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  reliability\nFROM machine\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  account_credit AS \"Account credit\"\nFROM machine\nWHERE\n  $__unixEpochFilter(time) AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  (((sum(power_consumption) + $power_offset) / 1000) * $power_cost) * ((($__to - $__from) / 1000) / 60 / 60)  AS \"Power Cost      \"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) and\n  machine_id = $machine_id\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__unixEpochGroupAlias(time,1s),\n  ((sum(power_consumption) + $power_offset) / 1000) * $power_cost AS \"Avg. Power cost p/h\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time)\n  and machine_id = $machine_id\nGROUP BY 1\nORDER BY $__unixEpochGroup(time,1s)"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"Power consumption\",\n  hw_id AS \"HW ID\",\n  component AS \"Component\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  power_consumption != '' AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"CPU\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'cpu' AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"GPU 1\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 1 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"GPU 2\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 2 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"GPU 3\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 3 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"GPU 4\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 4\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"GPU 5\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 5 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"GPU 6\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 6 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  temperature AS \"GPU 0\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 0 AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Rental Prices",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  earning AS \"GPU 1\"\nFROM instance\nWHERE\n  $__unixEpochFilter(time) AND\n  instance_id = 1 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  earning AS \"GPU 2\"\nFROM instance\nWHERE\n  $__unixEpochFilter(time) AND\n  instance_id = 2 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  earning AS \"GPU 3\"\nFROM instance\nWHERE\n  $__unixEpochFilter(time) AND\n  instance_id = 3 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  earning AS \"GPU 4\"\nFROM instance\nWHERE\n  $__unixEpochFilter(time) AND\n  instance_id = 4 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  earning AS \"GPU 5\"\nFROM instance\nWHERE\n  $__unixEpochFilter(time) AND\n  instance_id = 5 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  earning AS \"GPU 0\"\nFROM instance\nWHERE\n  $__unixEpochFilter(time) AND\n  instance_id = 0 AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Power draw",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"CPU\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'cpu' AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"GPU 1\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 1 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"GPU 2\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 2 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"GPU 3\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 3 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"GPU 4\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 4 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"GPU 5\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 5 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"GPU 6\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 6 AND\n  machine_id = $machine_id\nORDER BY time"
    },
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  power_consumption AS \"GPU 0\"\nFROM hardware\nWHERE\n  $__unixEpochFilter(time) AND\n  component = 'gpu' AND\n  hw_id = 0 AND\n  machine_id = $machine_id\nORDER BY time"
    }
   ]
  },
  {
   "title": "Reliability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  reliability\nFROM machine\nWHERE\n  $__unixEpochFilter(time)\nORDER BY time"
    }
   ]
  },
  {
   "title": "Docker events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  name,\n  val1 AS \"Container ID\",\n  val2 AS \"Image name\",\n  val3 AS \"GPU ID(s)\"\nFROM event\nwhere machine_id = $machine_id\nORDER BY time desc"
    }
   ]
  }
 ]
}